FROM nginx:alpine


COPY nginx.conf /etc/nginx/nginx.conf


COPY certs/server.crt /etc/nginx/certs/server.crt
COPY certs/server.key /etc/nginx/certs/server.key

EXPOSE 4499

CMD ["nginx", "-g", "daemon off;"]
